### ISSUE TITLE
Change the path to "watch"

### ISSUE THREAD

**Issue by Chithrak07** [AcroMedia/ansible-role-postfix#7]
Looks like /etc/resolv.conf is a symlink to /run/resolvconf/resolv.conf. Hence it is the later that we have to watch for changes.

**Comment by dale-c-anderson** [comment]
@Chithrak07 it looks like the path isn't the problem. 

- There's an [open systemd issue](https://github.com/systemd/systemd/issues/3639) which I'm interpreting to mean systemd follows symlinks by default, and
- There are log entries that show a new issue with our solution: 
  ```
  Jan 27 08:29:11 myserver systemd[1]: Reloading.
  Jan 27 08:29:12 myserver systemd[1]: /etc/systemd/system/etc-resolv-conf-watcher.path:2: Trigger cannot be of same type, ignoring: etc-resolv-conf-watcher.path
  Jan 27 08:29:12 myserver systemd[1]: Reloading.
  Jan 27 08:29:12 myserver systemd[1]: /etc/systemd/system/etc-resolv-conf-watcher.path:2: Trigger cannot be of same type, ignoring: etc-resolv-conf-watcher.path
  Jan 27 08:29:12 myserver systemd[1]: Starting resolvconf-pull-resolved.service...
  Jan 27 08:29:12 myserver systemd[1]: Mounting Mount unit for core20, revision 1328...
  Jan 27 08:29:12 myserver systemd[1]: Started resolvconf-pull-resolved.service.
  Jan 27 08:29:12 myserver systemd[1]: Mounted Mount unit for core20, revision 1328.
  Jan 27 08:29:13 myserver systemd[1]: Reloading.
  Jan 27 08:29:13 myserver systemd[1]: /etc/systemd/system/etc-resolv-conf-watcher.path:2: Trigger cannot be of same type, ignoring: etc-resolv-conf-watcher.path
  Jan 27 08:29:13 myserver systemd[1]: Starting Daily apt download activities...
  Jan 27 08:29:13 myserver systemd[1]: Starting resolvconf-pull-resolved.service...
  Jan 27 08:29:13 myserver systemd[1]: Reloading.
  Jan 27 08:29:13 myserver systemd[1]: /etc/systemd/system/etc-resolv-conf-watcher.path:2: Trigger cannot be of same type, ignoring: etc-resolv-conf-watcher.path
  Jan 27 08:29:13 myserver systemd[1]: Started resolvconf-pull-resolved.service.
  ```
  except I have no idea what this message actually means :laughing: :sob: 


Besides the above, I think we may want to try changing our `PathChanged` [directive](https://github.com/AcroMedia/ansible-role-postfix/blob/3841fb41deb2c862540698021ffb2402e7974c51/templates/etc/systemd/system/etc-resolv-conf-watcher.path.j2#L3) to become `PathModified`. According to the [docs](https://www.freedesktop.org/software/systemd/man/systemd.path.html), PathChanged only triggers "if the file opened for writing was closed", and PathModified triggers on "simple writes to the file", whatever those two things mean. If the authors of systemd followed the naming convention of the kernel, then answer at https://askubuntu.com/a/600859/119639 leads me to believe the difference between PathChanged and PathModified is that the first watches the inode, and the second watches it's contents.

**Comment by dale-c-anderson** [comment]
Ohhhhh @Chithrak07 I think the error message is pointing to [this line](https://github.com/AcroMedia/ansible-role-postfix/blob/3841fb41deb2c862540698021ffb2402e7974c51/templates/etc/systemd/system/etc-resolv-conf-watcher.path.j2#L2) - we're creating a circular reference. It needs to call the service, not the path.
